M48
; DRILL file KiCad 10.0.0 date 2026-06-20T16:59:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-20T16:59:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X30.25Y-22.0
X31.35Y-22.0
T2
X19.75Y-22.5
X19.75Y-27.5
M30
